/**
 * Google Search Console "HTML file" verification support.
 *
 * GSC asks for a file like /googleXXXXXXXX.html at the site root, containing:
 *   google-site-verification: googleXXXXXXXX.html
 *
 * The filename is generated by GSC and can differ from the meta-tag token,
 * so a rewrite in next.config.mjs routes any /google*.html request here and
 * we echo the exact filename back as the verification line.
 */

const FILENAME_PATTERN = /^google[0-9A-Za-z_-]+\.html$/;

export async function GET(request: Request): Promise<Response> {
  const { searchParams } = new URL(request.url);
  const file = searchParams.get("file") ?? "";

  if (!FILENAME_PATTERN.test(file)) {
    return new Response("Not found", { status: 404 });
  }

  return new Response(`google-site-verification: ${file}\n`, {
    status: 200,
    headers: { "Content-Type": "text/html; charset=utf-8" },
  });
}
