import { NextRequest, NextResponse } from "next/server";

/**
 * Google Search Console "HTML file" verification.
 *
 * GSC requests a file like /googleXXXXXXXX.html at the site root and expects
 * the body to be exactly:
 *   google-site-verification: googleXXXXXXXX.html
 *
 * The token is generated by GSC and can differ from the meta-tag token, so we
 * serve ANY /google*.html request dynamically with the matching verification
 * line. Middleware runs before the filesystem, so this needs no rewrites.
 */

const VERIFICATION_FILE = /^\/google[0-9A-Za-z_-]+\.html$/;

export function middleware(request: NextRequest) {
  const { pathname } = request.nextUrl;

  if (VERIFICATION_FILE.test(pathname)) {
    const file = pathname.slice(1);
    return new Response(`google-site-verification: ${file}\n`, {
      status: 200,
      headers: { "Content-Type": "text/html; charset=utf-8" },
    });
  }

  return NextResponse.next();
}

export const config = {
  // Run on all request paths except Next.js internals.
  matcher: ["/((?!_next/).*)"],
};
